# Generated by Django 5.0.1 on 2024-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
