# Generated by Django 5.0.6 on 2024-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orders_order_id_orders_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="delivery_address",
            field=models.TextField(default="sample address"),
        ),
    ]
